### ISSUE TITLE
"As_bytes" vs "to_bytes"

### ISSUE THREAD

**Issue by dtolnay** [Diggsey/c_fixed_string-rs#2]
CFixedStr has `to_bytes` while CFixedString has `as_bytes`. The "as" naming convention is typically for things that are essentially free, whereas both of these methods need to search the string for \0. I would expect both to use the "to" naming convention.

**Comment by Diggsey** [comment]
Interesting, I just copied the naming from `CString`/`CStr` - I wasn't aware of the convention. In that case I'll just remove the `as_` variants, as it should dereference to the `to_` variants anyway.

**Comment by Diggsey** [comment]
I kept the `as_` variants for `as_bytes(_mut)?_full` since they really are zero cost.
